---
- name: Install Zabbix official repository (RedHat)
  yum:
    name: "{{ zabbix_repo_official_package[zabbix_repo_version | string][ansible_distribution_major_version] }}"
    state: present
  when: ansible_os_family == "RedHat"

- block:
    - name: Install Zabbix official repository (Debian)
      apt:
        deb: "{{ zabbix_repo_official_package[zabbix_repo_version | string][ansible_distribution_major_version] }}"
        state: present

    - name: Pin Zabbix official repository (Debian)
      copy:
        dest: /etc/apt/preferences.d/zabbix
        content: |
          Package: zabbix-*
          Pin: origin repo.zabbix.com
          Pin-Priority: {{ zabbix_repo_apt_pin_priority }}
      when: zabbix_repo_apt_pin | bool
  when: ansible_os_family == "Debian"
